[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32dev
framework = arduino, espidf

board_build.sdkconfig = sdkconfig.esp32dev

lib_deps = 
    adafruit/DHT sensor library@^1.4.7
    arduino-libraries/LiquidCrystal@^1.0.7
    